### ISSUE TITLE
[Question] Dynamic DragSource

### ISSUE THREAD

**Issue by ely-alamillo** [cormacrelf/angular-skyhook#13]
The docs say you can have a dynamic dragSource if you pass null as the type but don't say what to do after that. Would you mind pointing me in the right direction or providing an example to get this working ?

**Comment by cormacrelf** [comment]
Which docs page mentions them but doesn’t link to anything? I have a lot of links but might have missed one. I think you’re looking at https://cormacrelf.github.io/angular-skyhook/injectables/SkyhookDndService.html#dragSource — there might be a compodoc issue preventing the rest of the parameter documentation being rendered, because I’m pretty sure there’s a link at the end of that sentence.

You’re looking for this

https://cormacrelf.github.io/angular-skyhook/interfaces/DragSource.html#setType

Or

https://cormacrelf.github.io/angular-skyhook/directives/DragSourceDirective.html#dragSourceType

**Comment by cormacrelf** [comment]
(Also, lots of the example code uses this. Check out ‘nested sources’.)
