### ISSUE TITLE
Using one DragSource / DropTarget object on multiple directives / DOM elements.

### ISSUE THREAD

**Issue by DirtZERO** [cormacrelf/angular-skyhook#224]
I guess this is a feature request though its possible I'm just doing it wrong.

The use case:
I have a component with an ngFor inside of it. I'd like to make the Element within this list draggable / droppable. They all need to do the same thing and they are quite simple or a Material2 component so I don't wan't to break them into my own component. I'd like to define one DragSource / DropTarget and have that work for all of them.

Current behavior: 
It will work only on the last one in the list.

Now I understand that there are obvious workarounds ( make my own component for the items in the ngFor or make an array of DragSource / DropTarget and associate them with each Element ) so if this doesn't work with how your connections are set up I understand. Hopefully this is not a waist of your time but I'm trying to replace a simple Dnd implementation I made (That didn't run outside of the global zone So Its REALLY SLOW) with yours and I'm having to re-work a lot. This would have been helpful and my co-worker suggested I ask you what you think.

Thank you for you time.

**Comment by cormacrelf** [comment]
If you’re making them sortable, use the sortable library. Otherwise, take inspiration from the sortable library, and use a directive! Recall that components are just directives with a template. You’ll see that the sortable’s ssRender directive attaches both a drop target and drag source to its host element. You can copy this pattern without the baggage of its weird prop passing.

**Comment by DirtZERO** [comment]
Awesome thank you again for your help!
