### ISSUE TITLE
Implementing multiple sortable containers from scratch (no ngRx)

### ISSUE THREAD

**Issue by killface** [cormacrelf/angular-skyhook#243]
After banging my head against ng2-dragula for days, I'm trying to use @angular-skyhook/sortable as a replacement. The basic functionality I'm looking for is multiple lists, with cards that can be dragged between them (and reordered). For better or for worse, I'm not using NgRx.

Everything was pretty straightforward, except I'm struggling to get good hover previews to work. Is the general idea (when not using NgRx) that I need to add logic to the hover() method that adds my card to a list, and removes it from other lists as well? It seems strange that hovering over one list would have to update the other lists, but I'm probably missing something.

I feel like this would be another good example to add (multiple simple lists without NgRx), and I'd be happy to add it myself if I can ever figure it out. Any guidance would be much appreciated.

**Comment by cormacrelf** [comment]
You can still use immutable data structures without ngrx. It makes programming this easier. Use the “immer” library, it’s only like 2kB. The morphing quiz example does this, I believe.

As for hover, the way it’s implemented in the examples with immutable lists is that you have to produce a new version of the list-of-lists. To preserve cancel-ability, you keep the old one around, and it simplifies things to implement hover with the same code that moves things for real, because the requirements of hover are pretty much identical to moving:

* a normal move, usually done in `drop` that takes the old list-of-lists and moves the card, producing a new list-of-lists
* a hover, which takes the old list-of-lists and moves the card to exactly the same place (“under the mouse”), producing a new list-of-lists

You don’t have to do that, you could always just “move it back” to cancel, but cancelling is way easier when you do it this way.

I’m not going to code up what it looks like when you just mutate lists in flight, because it’s painful and frankly a waste of time. If any clojure developers looked at Dragula/ng2-dragula and this list-mutating madness, they would have to put their spaceships on autopilot for a moment to fall over laughing. Yes it could be done, but save yourself the trouble.

**Comment by killface** [comment]
Thanks for getting back to me so quickly. I'll give Immer a shot today, and hopefully save myself a headache and learn something as well.

Also, I notice Immer's readme has a button for buying the developer a coffee to say thanks. I don't know how you feel about asking for donations, but some of us do like to thank the good people like you who make our lives easier with these public projects.

**Comment by cormacrelf** [comment]
@killface looks like I thought about it 8 months ago but never added a button. It's a good idea.

Hope you figured out your thing.
