### ISSUE TITLE
How to make kanban board with sub-cards

### ISSUE THREAD

**Issue by hassanasad** [cormacrelf/angular-skyhook#327]
Hi, I saw the kanban example you posted. Its quite good for an advanced level developer but for a novice like me it's complicated - primarily because of NgRx integration. Is it possible to simplify it?

Also i wanted help how to add sub-cards to that board? I have been trying myself for couple of days but it becomes quite messy. At this point i have tried Dragula, Angular CDK and Skyhook twice but cant seem to get close to what i want.

Any help or direction in this regard will be greatly appreciated.

**Comment by cormacrelf** [comment]
You want complicated behaviour, you get complicated code. I don’t have the time to rewrite it without NGRX, especially because it wouldn’t look all that different or teach people anything new about this library. Maybe at some point, but it’s up to you for now.

I don’t know precisely what you mean by sub-cards, but whatever it is, it won’t be fundamentally more complex than the existing two level structure. It’s just another level, right? It would be easier to program with an immutable helper like `immer`, rather than DIYing the immutable lists like I did. (Also... three levels with sub-cards? That is probably beyond the mental agility of your average user. I don’t even want to know why you need to build this.)

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by hassanasad** [comment]
Thanks the suggestion, i will have a look at `immer`.
Basically what i mean by cards is tasks and then subtasks.

I am trying to merge the kanban (sorting) example with your drilldown example but they both are far apart in terms of code base.

**Comment by cormacrelf** [comment]
Yeah they're different - one is a tree that can be infinitely deep but with each level having the same kind of content. Your levels are different datatypes, so you code them one by one and you can't use any of the tree code. You can reuse the activatorDropTarget because it's purely visual. I would probably open a modal to deal with the sub-tasks, with another (fullscreen) activatorDropTarget behind it to get out of it again.

**Comment by hassanasad** [comment]
I want to keep it really basic. Just trying to understand how to be able to make nested draggables all running from singular flattish data structure. 

Here is a screenshot:
<img width="897" alt="Screenshot 2019-03-23 12 33 03" src="https://user-images.githubusercontent.com/7580112/54863246-29848900-4d68-11e9-84f1-a7f9c6f1ada0.png">

Wanted to make it draggable with few rules for instance:
1. Area can be sorted (up and down).
2. Task can be sorted within an Area or moved to another Area (along with sub-tasks if any).
3. Sub-tasks can be sorted within its parent Task And also pulled out to make it a parent Task.
4. A Task that has sub-tasks should not be allowed in sub-tasks area.
5. A single task can be dragged onto another single task to convert it into a sub-task.

I was able to do 1 and 2 with Dragula but then it got too complicated with setting up other rules so had to scratch that. Now trying Skyhooks. 
With Skyhooks when I setup nested drag handles (those grey circles), thats when it becomes weird.

**Comment by cormacrelf** [comment]
Ok, so:

* Drag handles using sortable should follow how the kanban board does it (inject `@Optional() render: SkyhookSortableRender<WhateverType>` on the child + `<div [dragSource]="render?.source">` in the child template)
* Watch https://github.com/cormacrelf/angular-skyhook/issues/274#issuecomment-465331666 for drag handles; make sure the handle div originates at the top left corner.
* Your data structure is mostly good, it will be convenient to look up parents as long as you store the parent id on each level. However you should not have `IArea.tasks` duplicating data. Just store the associated ids, and use a function to pull the real tasks out with `.map(id => db.tasks[id])`. Otherwise you may as well not have it 'flat' at all.
* For when you want a sub-task to turn into a task:

  * I don't think this can be done at the moment; the list that holds tasks would need to accept an array of DND types, i.e. `["TASK", "SUB_TASK"]`. At the moment, it only accepts what it produces.
  * Ideally, you could tell it to emit `"TASK"` but accept either. I'll have a look at this.

**Comment by hassanasad** [comment]
Thanks for detailed explanation, I will have a go at it.

I have tried using that approach from the kanban sample `@Optional()` and attaching it using `[dragSource]` and thats how i face a weird issue. Let me modify my code to grab a screenshot if i can.

I thought `IArea.tasks` were being reference copied because of Javascript nature with arrays in general :) - Your proposed method makes more sense though, will update my Datastructure.

Sorry i didn't understand much regarding your proposed solution for sub-task turn into task. In my head i thought if i change the `parentId` of task, it would suffice, no?

**Comment by cormacrelf** [comment]
No need to screenshot the weird issue, I already know.

It's technically not a property of arrays, it's a property of objects. But it won't work well with Immer, so that's why. Also the performance implications of computing that list are EXACTLY why you would want to use @ngrx and its memoized selectors. But sure.

The problem with sub-/tasks is not that you can't turn one into the other... it's that you can't drag them into the same list. The idea is that once you drag it into a differently-typed list, you do whatever you need to turn a sub-task into a normal task, but you have to get to that point first. Unless you actually made this thing *really* flat, more like the drilldown example, but that has enormous implications for how you store all this in SQL or whatever db you use, at the end of the day.

I will publish a new `@angular-skyhook/sortable` with an extra property on the `SortableSpec` called `accepts` (which can be an array) to cater to this in a bit.

**Comment by cormacrelf** [comment]
Update: `@angular-skyhook/sortable@1.2.0` published. There's also a new simpler kanban example that should be built on the examples page shortly.

**Comment by hassanasad** [comment]
> Also the performance implications of computing that list are EXACTLY why you would want to use @ngrx and its memoized selectors
Oh i agree with you on that. I just wanted to do it without NgRx simply because of its learning curve.

Thanks for the new version, let me check it out to see if it eases my pain ;)
I have been stuck on this experiment project for days now.

**Comment by cormacrelf** [comment]
btw I should also mention -- you probably want your structure to look like this:

```typescript
interface Database {
    tasks: { [id: string]: Task },
    areas: { [id: string]: Area },
}

interface Task {
    id: number;
    title: string;
}

interface Area {
    id: number;
    title: string;
    tasks: Array<number>;
}

let db: Database = {
    tasks: { 1: { id: 1, title: "yeah" } },
    areas: { 10: { id: 10, title: "area", tasks: [1] } },
};

function tasksForArea(db: Database, a: number) {
    return db.areas[a].tasks.map(id => db.tasks[id]);
}

console.log(tasksForArea(db, 10));
```

**Comment by hassanasad** [comment]
hmm, i am little confused. Wouldn't `Map` be a better data structure to use? Also I wanted to keep Tasks independent of Area data (`areaId`). That way i would just look at Areas and fetch Task from main DB, no?

Kinda like:
```typescript
interface Database {
    tasks: Map<number, Task>,
    areas: Map<number, Area>,
}
```

**Comment by cormacrelf** [comment]
Map? Not if you want to use Immer, not compatible. Anyway, I explained why, but it's up to you.

**Comment by hassanasad** [comment]
Thanks Cormacrelf for your support. Unfortunately i couldn't complete my test project using skyhooks.  Seems like i need to upgrade my Angular skills. I completed it using ng2-Dragula for now (Not the best approach probably as its little hard to extend certain aspects of it). Maybe i will comeback to this library again when my understanding grows a bit more.
